add home page
WildCodeSchool/tlse0321-js-p2-little-hero-academy pull request #103
Opened 2021-05-03 07:57 UTC by KB31400

2021-05-03 08:18 UTC, esiomlink approved these changes

2021-05-04 21:18 UTC, CharlotteLu31 approved these changes

2021-05-05 07:30 UTC, Froyj requested changes

2021-05-05 07:30 UTC, Froyj commented on src/Components/HomePage.jsx
> +const homePage = () => (
en majuscule

2021-05-05 08:01 UTC, esiomlink approved these changes

2021-05-05 11:46 UTC, Froyj approved these changes

2021-05-05 11:49 UTC, merged