Validation quiz
WildCodeSchool/tlse0321-js-p2-little-hero-academy pull request #52
Opened 2021-04-22 16:13 UTC by CharlotteLu31

2021-04-22 17:07 UTC, KB31400 approved these changes

2021-04-23 07:07 UTC, jeromeBor approved these changes

2021-04-23 08:37 UTC, Froyj requested changes
- merge modif-geo dans cette branche
- importer les questions depuis un fichier externe (range dans  un dossier constants)

2021-04-23 09:43 UTC, Froyj approved these changes

2021-04-23 10:46 UTC, merged